# Generated by Django 5.2.4 on 2025-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('almost_done', 'Almost Done'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
    ]
