# Generated by Django 5.2.4 on 2025-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('almost_done', 'Almost Done'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='in_stock', max_length=20),
        ),
    ]
