# Generated by Django 5.2.5 on 2025-08-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_supplier_email_supplier_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('almost_done', 'Almost Done'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
